function testThrowErrorSuggestions() {
    error err = error("Error Occurred!!");

    try {
        
    } catch(error err2) {

    } finally {
        throw 
    }
}